import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../globals.css';
import NavBar from '@/components/nav/nav-bar';
import { SessionProvider } from 'next-auth/react';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/sonner';
import { NextIntlClientProvider, useMessages } from 'next-intl';

const poppins = Poppins({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	const messages = useMessages();

	return (
		<html lang={locale}>
			<body className={poppins.className}>
				<NextIntlClientProvider messages={messages} locale={locale}>
					<ThemeProvider
						attribute='class'
						defaultTheme='light'
						// enableSystem
						disableTransitionOnChange>
						<SessionProvider>
							<NavBar />
							{children}
							<Toaster />
						</SessionProvider>
					</ThemeProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
